import { Visibility, VisibilityOff } from "@mui/icons-material"
import { IconButton, InputAdornment, OutlinedInput } from "@mui/material"
import Head from "next/head"
import React from "react"
import ButtonDefault from "../../components/ButtonDefault/ButtonDefault"
import HeaderDefault from "../../components/HeaderDefault/HeaderDefault"
import { LoginFormStyled, LoginMainContainer, LoginPageContainer } from "./styles"

interface State {
  email: string;
  password: string;
  showPassword: boolean;
}

function LoginPage() {
  const [values, setValues] = React.useState<State>({
    email: '',
    password: '',
    showPassword: false,
  });

  const handleChange =
    (prop: keyof State) => (event: React.ChangeEvent<HTMLInputElement>) => {
      setValues({ ...values, [prop]: event.target.value });
    };

  const handleClickShowPassword = () => {
    setValues({
      ...values,
      showPassword: !values.showPassword,
    });
  };

  const handleMouseDownPassword = (event: React.MouseEvent<HTMLButtonElement>) => {
    event.preventDefault();
  };

  return (
    <>
      <LoginPageContainer>
        <Head>
          <title>IgnisFlix | Login</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <LoginMainContainer>
          <HeaderDefault isIconExists={true} />

          <div>
            <p>E-mail / username</p>
            <LoginFormStyled variant="outlined">
              <OutlinedInput
                id="email"
                type="text"
                value={values.email}
                onChange={handleChange('email')}
              />
            </LoginFormStyled>

            <p>Senha</p>
            <LoginFormStyled variant="outlined">
              <OutlinedInput
                id="password"
                type={values.showPassword ? 'text' : 'password'}
                value={values.password}
                onChange={handleChange('password')}
                endAdornment={
                  <InputAdornment position="end">
                    <IconButton
                      aria-label="toggle password visibility"
                      onClick={handleClickShowPassword}
                      onMouseDown={handleMouseDownPassword}
                      edge="end"
                    >
                      {values.showPassword ? <VisibilityOff /> : <Visibility />}
                    </IconButton>
                  </InputAdornment>
                }
              />
            </LoginFormStyled>
          </div>

          <ButtonDefault text={`Entrar`} path={`/movies`} />

        </LoginMainContainer>
      </LoginPageContainer>
    </>
  )
}

export default LoginPage;