import { IconButton, InputAdornment, OutlinedInput, Paper } from "@mui/material"
import SearchIcon from '@mui/icons-material/Search'
import Head from "next/head"
import React, { useEffect, useState } from "react"
import HeaderDefault from "../../components/HeaderDefault/HeaderDefault"
import { MoviesFormStyled, MoviesMainContainer, MoviesPageContainer } from "./styles"
import { NextPage } from "next"
import { getMoviesService } from "../../services"
import { IMovies } from "../../services/getMovies/types"
import ButtonDefault from "../../components/ButtonDefault/ButtonDefault"


const MoviesPage: NextPage = () => {
  const [movies, setMovies] = useState<IMovies[]>([])
  const user = typeof window !== "undefined" ? JSON.parse(localStorage.getItem('user') ?? '') : ''

  useEffect(() => { handleGetMovies() }, []);

  const handleGetMovies = async () => {
    try {
      const { results } = await getMoviesService.getMovies()
      setMovies(results)
    } catch (error) {
      console.log(error)
    }
  }

  return (
    <>
      <MoviesPageContainer>
        <Head>
          <title>IgnisFlix | Movies</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <MoviesMainContainer>
          <HeaderDefault isIconExists={true} />

          <div>
            <h1><span>Bem vindo</span>, </h1>

            <MoviesFormStyled>
              <OutlinedInput
                placeholder="Buscar filme"
                endAdornment={
                  <InputAdornment position="end">
                    <IconButton
                      type="button"
                      edge="end"
                    >
                      <SearchIcon />
                    </IconButton>
                  </InputAdornment>}
              />

            </MoviesFormStyled>

            <h1>Filmes</h1>
            {movies.map(movie => (
              <p>{movie.title}</p>
            ))}
          </div>

          <ButtonDefault text="Ver mais" onClick={() => { console.log('clicou') }} />
        </MoviesMainContainer>
      </MoviesPageContainer>
    </>
  )
}

export default MoviesPage;