import { IconButton, InputAdornment, OutlinedInput, Paper } from "@mui/material"
import SearchIcon from '@mui/icons-material/Search'
import Head from "next/head"
import React from "react"
import HeaderDefault from "../../components/HeaderDefault/HeaderDefault"
import { MoviesFormStyled, MoviesMainContainer, MoviesPageContainer } from "./styles"


function MoviesPage() {

  return (
    <>
      <MoviesPageContainer>
        <Head>
          <title>IgnisFlix | Movies</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <MoviesMainContainer>
          <HeaderDefault isIconExists={true} />

          <div>
            <h1><span>Bem vindo</span>, Marcelo</h1>

            <MoviesFormStyled>
              <OutlinedInput
                placeholder="Buscar filme"
                endAdornment={
                  <InputAdornment position="end">
                    <IconButton
                      type="button"
                      edge="end"
                    >
                      <SearchIcon />
                    </IconButton>
                  </InputAdornment>}
              />

            </MoviesFormStyled>

          </div>
        </MoviesMainContainer>
      </MoviesPageContainer>
    </>
  )
}

export default MoviesPage;