import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import ButtonDefault from '../components/ButtonDefault/ButtonDefault';
import HeaderDefault from '../components/HeaderDefault/HeaderDefault';
import { HomeMainContainer, HomePageContainer, PersonaContainer, SloganContainer } from './styles';
import { motion } from "framer-motion";
import { useEffect, useState } from 'react';

const Home: NextPage = () => {
  const router = useRouter();
  const [isTokenExists, setIsTokenExists] = useState(false);
  useEffect(() => setIsTokenExists(localStorage.getItem('accessToken') !== null ? true : false), []);

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.5 }}
    >
      <HomePageContainer>
        <Head>
          <title>IgnisFlix</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <HomeMainContainer>
          <HeaderDefault isIconExists={false} />

          <SloganContainer>
            <h1 >Do sofá pro seu celular</h1>
            <h2>A revolução do cinema na sua casa.</h2>
          </SloganContainer>

          <PersonaContainer>
            <img
              src="/persona.svg"
              alt="Imagem circular com uma pessoa no centro sorridente com o celular nas mãos, ícone de pipoca no quadrante superior esquerdo e ícone de som no quadrante inferior direito. Ao redor da imagem, há linhas circulares indicando visualmente som"
            />
          </PersonaContainer>

          <ButtonDefault text={`Começar a ver filmes`} onClick={isTokenExists ? () => { router.push('movies') } : () => { router.push('login') }} />

        </HomeMainContainer>


      </HomePageContainer>
    </motion.div>
  )
}

export default Home;
